### ISSUE TITLE
Fix `datauri` method on Windows and Ruby 3.0

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-utils#20]
As per: https://github.com/metanorma/metanorma-standoc/issues/672#issuecomment-1237664341

From @opoudjis :

`Metanorma::Utils::datauri(i["src"], @localdir)` in Windows is returning empty for PlantUML-generated images, so nothing is being passed on to png_validate1.

This happens in standoc, bin/rspec --format doc spec/metanorma/datamodel/diagram_preprocessor_spec.rb

There may well be a Windows-specific bug in metanorma-utils, but I can't identify what it is.

The code is at:
https://github.com/metanorma/metanorma-utils/blob/49aa66827c01d49f2aa7df26209222a1e3a1d137/lib/utils/image.rb#L129-L175

This code needs to be rewritten and specs added.

For example, this method does not need to exist, i.e. no file write needs to happen, because `Marcel::MimeType.for(...)` supports direct binary data in the argument (in the `IO` class).

https://github.com/metanorma/metanorma-utils/blob/49aa66827c01d49f2aa7df26209222a1e3a1d137/lib/utils/image.rb#L164-L175

**Comment by ronaldtse** [comment]
Please do this in https://github.com/metanorma/metanorma-utils/pull/new/rt-fix-datauri

**Comment by opoudjis** [comment]
Ronald's fix was buggy, and therefore failed to address the actual issue.

**Comment by ronaldtse** [comment]
@opoudjis indeed, the URL matching should really only match https and http. One additional problem here is that this gem does not test datauri using Windows paths.

**Comment by opoudjis** [comment]
The issue turns out to be that, when we run PlantUML in Windows, it is generating an image, but the image is of size 0. Have just confirmed this by inserting diagnostics in lib/metanorma/standoc/cleanup_image.rb, when  running spec/metanorma/datamodel/diagram_preprocessor_spec.rb

````
def img_cleanup(xmldoc)
        if @datauriimage
          xmldoc.xpath("//image").each do |i|
            # do not datauri encode SVG, we need to deduplicate its IDs
            unless read_in_if_svg(i, @localdir)
              warn "i[src]"
warn i["src"]
local_path = i["src"]
        relative_path = File.join(@localdir, i["src"])

        # Check whether just the local path or the other specified relative path
        # works.
        path = [local_path, relative_path].detect do |p|
          File.exist?(p) ? p : nil
        end
              warn "path"
        warn path
        warn "exist?"
        warn File.exist?(path)
        warn "size"
        warn File.size(path)
              warn "Marcel"
        warn Marcel::MimeType.for(Pathname.new(path))
              warn "binread"
              warn File.binread(path).size
        bin = File.binread(path)
              warn "data"
        data = Base64.strict_encode64(bin)
        warn data
        warn "end"

              i["src"] = Metanorma::Utils::datauri(i["src"], @localdir)
            end
          end
        end
        svg_uniqueids(xmldoc)
        xmldoc
      end
````

In Ubuntu and Mac, the file exists and is 53k. In Windows, it is exists, but is of size 0 (and we have not checked this until now, with the introduction of pngcheck.)

The running of Plantuml is done in lib/metanorma/standoc/macros_plantuml.rb

This is happenig both with Raw PlantUML passed for processing, and with diagrams being converted into PlantUML, through the code in  lib/metanorma/standoc/datamodel, is barfing in Windows. So there is something in the machine-generated PlantUML, which Windows does not like. This is not a general PlantUML issue.

I don't know why @alexeymorozov has failed to replicate this, but @CAMOBAP, I have to turn this over to you. The issue was raised in https://github.com/metanorma/metanorma-standoc/issues/672, but is still not resolved.

https://github.com/metanorma/metanorma-standoc/actions/runs/3047044444/jobs/4910586724

Test branch: test/20220914, which all but one rspec file removed.

**Comment by CAMOBAP** [comment]
On it

**Comment by CAMOBAP** [comment]
@opoudjis https://github.com/metanorma/metanorma-standoc/pull/685 - ready for review

**Comment by ronaldtse** [comment]
Thank you @CAMOBAP !

**Comment by opoudjis** [comment]
Thank you so much @CAMOBAP !
